// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBojzjzo4PH4UA_oI4avm4w1ooZEjWPmPc',
    appId: '1:562639468353:android:dfc8a0dd00c41543c8d3c0',
    messagingSenderId: '562639468353',
    projectId: 'orderherfood-delivery',
    databaseURL: 'https://orderherfood-delivery-default-rtdb.firebaseio.com',
    storageBucket: 'orderherfood-delivery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9wJfG8jUZpC_dEA-V5k_KUj06OZXbp7A',
    appId: '1:562639468353:ios:a6d790f9fcf8011bc8d3c0',
    messagingSenderId: '562639468353',
    projectId: 'orderherfood-delivery',
    databaseURL: 'https://orderherfood-delivery-default-rtdb.firebaseio.com',
    storageBucket: 'orderherfood-delivery.appspot.com',
    iosBundleId: 'com.orderherfood.delivery',
  );
}
